# Generated by Django 2.0.2 on 2018-02-18 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=256)),
                ('char', models.CharField(max_length=256)),
                ('translit', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('sort_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=256)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Letter')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Page')),
            ],
        ),
    ]
