# Generated by Django 2.0.2 on 2018-02-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='root',
            name='homophone',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
